name: 'Hax Auto Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....' 
        run: |
          cmd /c curl -sSL -O https://raw.githubusercontent.com/pd542/xah/master/HaxAutoReNew.exe
          cmd /c HaxAutoReNew.exe -user ${{ secrets.USERNAME_LIST }} -password  ${{ secrets.PASSWORD_LIST }}
